# Generated by Django 5.0.3 on 2024-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('DIARY', '일기'), ('STUDY', '공부'), ('ETC', '기타')], max_length=20),
        ),
    ]
