# Generated by Django 5.0.3 on 2024-03-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='user_id',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comments', models.TextField(verbose_name='코멘트')),
                ('user_id', models.IntegerField(verbose_name='유저 아이디')),
                ('is_secret', models.BooleanField(default=False, verbose_name='비밀여부')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
