# Generated by Django 5.0.3 on 2024-03-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_writer_post_user_id_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(max_length=10, verbose_name='유저 아이디'),
        ),
    ]
