# Generated by Django 5.0.3 on 2024-04-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_post_id_alter_comment_user_id_and_more'),
        ('posts', '0005_alter_comment_is_secret'),
    ]

    operations = [
    ]
